### ISSUE TITLE
MMM-M.js:63 Uncaught TypeError: Cannot read property 'alt' of undefined

### ISSUE THREAD

**Issue by fewieden** [cowboysdude/MMM-M#1]
every odd carousel item throws that error, after debugging it seems that every even item is a movie and the odd items are additional information

**Comment by cowboysdude** [comment]
Working on a fix for that.   Hopefully will have it today.   Scaling  back the amount of info to just what is needed.

**Comment by cowboysdude** [comment]
Couldn't fix it... project is dead.
